
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.calculadora.Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SUMA = 2;
  public static final int MULTIPLICACION = 4;
  public static final int EOF = 0;
  public static final int PARENTESIS_CERRADO = 7;
  public static final int NUMERO = 8;
  public static final int error = 1;
  public static final int DIVISION = 5;
  public static final int PARENTESIS_ABIERTO = 6;
  public static final int RESTA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "NUMERO"
  };
}

